name: rsas_env
channels:
- conda-forge
dependencies:
- annotated-types=0.7.0
- anyio=4.4.0
- aom=3.9.1
- atk-1.0=2.38.0
- bzip2=1.0.8
- ca-certificates=2024.7.4
- cairo=1.18.0
- certifi=2024.8.30
- cffi=1.17.1
- charset-normalizer=3.3.2
- colorama=0.4.6
- cryptography=43.0.0
- dav1d=1.2.1
- distro=1.9.0
- double-conversion=3.3.0
- et_xmlfile=1.1.0
- exceptiongroup=1.2.2
- expat=2.6.2
- fftw=3.3.10
- font-ttf-dejavu-sans-mono=2.37
- font-ttf-inconsolata=3.000
- font-ttf-source-code-pro=2.038
- font-ttf-ubuntu=0.83
- fontconfig=2.14.2
- fonts-conda-ecosystem=1
- fonts-conda-forge=1
- freetype=2.12.1
- fribidi=1.0.10
- gdk-pixbuf=2.42.12
- ghostscript=10.03.1
- giflib=5.2.2
- graphite2=1.3.13
- graphviz=12.0.0
- gtk2=2.24.33
- gts=0.7.6
- h11=0.14.0
- h2=4.1.0
- harfbuzz=9.0.0
- hpack=4.0.0
- httpcore=1.0.5
- httpx=0.27.2
- hyperframe=6.0.1
- icu=75.1
- idna=3.8
- imagemagick=7.1.1_38
- iniconfig=2.0.0
- jbig=2.1
- jiter=0.5.0
- krb5=1.21.3
- lcms2=2.16
- lerc=4.0.0
- libavif16=1.1.1
- libblas=3.9.0
- libcblas=3.9.0
- libclang-cpp16=16.0.6
- libclang13=18.1.8
- libcxx=18.1.8
- libde265=1.0.15
- libdeflate=1.21
- libedit=3.1.20191231
- libexpat=2.6.2
- libffi=3.4.2
- libgd=2.3.3
- libgfortran=5.0.0
- libgfortran5=13.2.0
- libglib=2.80.3
- libheif=1.18.2
- libiconv=1.17
- libintl=0.22.5
- libjpeg-turbo=3.0.0
- liblapack=3.9.0
- libllvm16=16.0.6
- libllvm18=18.1.8
- libopenblas=0.3.27
- libpng=1.6.43
- libpq=16.4
- librsvg=2.58.3
- libsqlite=3.46.0
- libtiff=4.6.0
- libwebp=1.4.0
- libwebp-base=1.4.0
- libxcb=1.16
- libxml2=2.12.7
- libxslt=1.1.39
- libzlib=1.3.1
- llvm-openmp=18.1.8
- mysql-common=8.3.0
- mysql-libs=8.3.0
- ncurses=6.5
- numpy=2.0.1
- openai=1.44.1
- openjpeg=2.5.2
- openpyxl=3.1.5
- openssl=3.3.1
- packaging=24.1
- pandas=2.2.2
- pango=1.54.0
- pcre2=10.44
- pdfminer.six=20221105
- pdfplumber=0.9.0
- perl=5.32.1
- pillow=10.4.0
- pip=24.2
- pixman=0.43.4
- pkg-config=0.29.2
- pluggy=1.5.0
- pthread-stubs=0.4
- pycparser=2.22
- pydantic=2.9.1
- pydantic-core=2.23.3
- pyside6=6.7.2
- pytest=8.3.3
- pytest-qt=4.4.0
- python=3.12.5
- python-dateutil=2.9.0
- python-tzdata=2024.1
- python_abi=3.12
- pytz=2024.1
- qt6-main=6.7.2
- rav1e=0.6.6
- readline=8.2
- ruff=0.6.1
- setuptools=72.1.0
- six=1.16.0
- sniffio=1.3.1
- svt-av1=2.2.1
- tk=8.6.13
- tomli=2.0.1
- tqdm=4.66.5
- typing-extensions=4.12.2
- typing_extensions=4.12.2
- tzdata=2024a
- wand=0.6.10
- wheel=0.44.0
- x265=3.5
- xorg-kbproto=1.0.7
- xorg-libice=1.1.1
- xorg-libsm=1.2.4
- xorg-libx11=1.8.9
- xorg-libxau=1.0.11
- xorg-libxdmcp=1.1.3
- xorg-libxext=1.3.4
- xorg-libxrender=0.9.11
- xorg-libxt=1.3.0
- xorg-renderproto=0.11.1
- xorg-xextproto=7.3.0
- xorg-xproto=7.0.31
- xz=5.2.6
- zlib=1.3.1
- zstd=1.5.6

