# https://docs.astral.sh/ruff/settings/

line-length = 80

exclude = [
    "modules/GUI/gui.py",
]

[lint]
extend-select = ["E501", "I001", "N801", "N807", "N811", "N812", "N813", "N814", "N999", "D", "UP", "YTT", "ANN", "Q", "RET", "SIM"]