name: "Test PR"

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
      - reopened

permissions:
  pull-requests: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: mamba-org/setup-micromamba@v1
      with:
        environment-file: environment.yml
    - name: Install packages
      run: |
        sudo apt-get update
        sudo apt install -y libegl1-mesa-dev qt6-base-dev xvfb libxcb-randr0 libxcb-cursor0 libxcb-xtest0 libxcb-xinerama0 libxcb-shape0
    - name: Run tests
      run: |
        Xvfb :99 -screen 0 1920x1080x24 &
        export DISPLAY=:99
        pytest
